### ISSUE TITLE
EvilCrive99 exposed

### ISSUE THREAD

**Issue by WiLLiAM111333** [EvilCrive/training-records#33]
I found this dirty silver peaker dog inting my aram, someone better do something about it cause Riot didnt

**Comment by WiLLiAM111333** [comment]
Zs

**Comment by acrivellari** [comment]
@WiLLiAM111333 dog

**Comment by WiLLiAM111333** [comment]
Maybe close it you dog

**Comment by acrivellari** [comment]
@WiLLiAM111333 INSANE DOG
